apiVersion: v1
kind: ConfigMap
metadata:
  name: fsdevops-backend-config
  labels:
    app.kubernetes.io/part-of: fsdevops-portfolio
    app.kubernetes.io/component: backend
data:
  ENVIRONMENT: "production"
  SERVER_PORT: "8080"
  DB_HOST: "fsdevops-db"
  DB_PORT: "5432"
  DB_NAME: "fsdevops"
  DB_USER: "fsdevops"
  DB_SSLMODE: "require"
  ALLOW_ORIGINS: "https://devops.azizedursun.com"
