apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fsdevops-ingress
  labels:
    app.kubernetes.io/part-of: fsdevops-portfolio
    app.kubernetes.io/component: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-connections: "5"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - devops.azizedursun.com
        - api.devops.azizedursun.com
      secretName: fsdevops-tls
  rules:
    - host: devops.azizedursun.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fsdevops-frontend
                port:
                  number: 3000
    - host: api.devops.azizedursun.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fsdevops-backend
                port:
                  number: 8080
