apiVersion: v1
kind: Service
metadata:
  name: fsdevops-backend
  labels:
    app: fsdevops-backend
    app.kubernetes.io/part-of: fsdevops-portfolio
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: fsdevops-backend
---
apiVersion: v1
kind: Service
metadata:
  name: fsdevops-frontend
  labels:
    app: fsdevops-frontend
    app.kubernetes.io/part-of: fsdevops-portfolio
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: fsdevops-frontend
