apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devops-journey
data:
  ENVIRONMENT: "production"
  SERVER_PORT: "8080"
  DB_PORT: "5432"
  DB_NAME: "devops_journey"
  DB_SSLMODE: "disable"
  ALLOW_ORIGINS: "https://your-domain.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: devops-journey
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://api.your-domain.com"
